### ISSUE TITLE
Element "pincode-button-wrapper" too small in android

### ISSUE THREAD

**Issue by LuisHCK** [HsuanXyz/ionic2-pincode-input#8]
Hi! I really love this plugin, is perfect.
I noticed that the buttons on android are smaller than on iOS.
Using the inspector I noticed that **ionic 3** makes buttons smaller in android.
### **BEFORE**
![captura de pantalla de 2017-06-28 10-23-26](https://user-images.githubusercontent.com/5175137/27649017-b4b31b04-5bed-11e7-8f4e-fad6cc35d782.png)
I fixed it this way:

```css
.pincode-wrapper {
  .button-md {
    height: 4.6rem !important; /* This fixes all */
    font-size: 1.8rem !important;
    font-weight: 300;
    color: #212121;
  }
}
```
### **AFTER**
![captura de pantalla de 2017-06-28 10-24-30](https://user-images.githubusercontent.com/5175137/27649232-603f7c9c-5bee-11e7-9c30-9f0cc38d9303.png)

Additionally, I made some adjustments to make it look beautiful

Thanks for making this beautiful plugin!

Saludos desde Nicaragua!
